Test intergiro acquirer
payfunc/upcheck pull request #15
Opened 2021-12-16 09:41 UTC by Magnus93

2021-12-16 12:44 UTC, robinnedergard requested changes

2021-12-16 12:44 UTC, robinnedergard commented on .circleci/config.yml
> +    description: "test"
```suggestion
    description: "test Clearhaus"
```

2021-12-16 12:44 UTC, robinnedergard commented on .circleci/config.yml
> +          cron: "2,12,22,32,42,52 * * * *"
```suggestion
          cron: "02,12,22,32,42,52 * * * *"
```

2021-12-16 12:44 UTC, robinnedergard commented on .circleci/config.yml
> +          name: Run tests
```suggestion
          name: Run Clearhaus tests
```

2021-12-16 12:44 UTC, robinnedergard commented on .circleci/config.yml
> +            -d from=PayFuncCI \
Why not UpCheck like the other one?
```suggestion
            -d from=UpCheck \
```

2021-12-16 12:44 UTC, robinnedergard commented on .circleci/config.yml
> +      - test-clearhaus
Should be test? We should run all test on build right? So that we know they work before merging.
```suggestion
      - test
```

2021-12-16 12:44 UTC, robinnedergard commented on .circleci/config.yml
> +      - clearhaus
```suggestion
      - clearhaus
      - intergiro
```

2021-12-16 12:44 UTC, robinnedergard commented on .circleci/config.yml
> +      - clearhaus
All test on build right?

2021-12-16 12:44 UTC, robinnedergard commented on .circleci/config.yml
> +      - clearhaus
Do test locally that the syntax is alright.

2021-12-16 13:26 UTC, Magnus93 commented on .circleci/config.yml
> +          cron: "2,12,22,32,42,52 * * * *"
According to circleci documentation it does not seam to be written with a leading zero. 
https://circleci.com/docs/2.0/workflows/#nightly-example
They use 1psoiz crontab:
https://www.unix.com/man-page/POSIX/1posix/crontab/

2021-12-16 13:27 UTC, robinnedergard commented on .circleci/config.yml
> +          cron: "2,12,22,32,42,52 * * * *"
Then the other cron-trigger needs to be changed. :)

2021-12-16 13:48 UTC, robinnedergard requested changes

2021-12-16 13:48 UTC, robinnedergard commented on .circleci/config.yml
> +      - intergiro
```suggestion
      - build
```

2021-12-16 13:48 UTC, robinnedergard commented on .circleci/config.yml
> +      - test-clearhaus
change this to test

2021-12-16 15:24 UTC, robinnedergard requested changes

2021-12-16 15:24 UTC, robinnedergard commented on .circleci/config.yml
> +      - clearhaus
```suggestion
```

2021-12-17 14:15 UTC, robinnedergard approved these changes

2021-12-20 13:26 UTC, fredrikbryntesson approved these changes

2021-12-20 13:26 UTC, merged